name: Atualizar Classificação

on:
  schedule:
    - cron: '0 6 * * *'  # Executa todos os dias às 6h UTC (3h BRT)
  workflow_dispatch:  # Permite executar manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script de classificação
        run: python codigo/classificacao.py
      
      - name: Commit e push dos dados atualizados
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dados/*.csv
          git commit -m "Atualiza classificação diária" || echo "Nenhuma mudança para commitar"
          git push
